### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by OWERLORD01** [MeGysssTaa/ReflexIssueTracker#40] opened 2017-05-25 13:38 UTC
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Console error / other

**Server version:** 1.11.2 tacospigot

**ProtocolLib version:** latest

**Reflex version:** latest (10)

**ViaVersion version (if present):** N/A
I'm using protocolsupport (latest dev build)

**A link to your server log if reporting a console error, or to Reflex log if reporting a bypass/false positive:**
https://hastebin.com/elorijinod.md

**Additional information (e.g. how to reproduce the issue you are experiencing):**
When reflex detects me or my players, it kicks them with disconnected message and this error appears in console. https://hastebin.com/elorijinod.md

I know that it probably isnt issue with your plugin, but what should i do?

**Comment by Vktre** [comment] 2017-05-25 13:54
Seems like a error with **ProtocolSupport** i am not sure.

**Comment by OWERLORD01** [comment] 2017-05-25 14:10
> Seems like a error with ProtocolSupport i am not sure.

I know, but I must use protocolsupport! Every server need this plugin!!!

**Comment by Vktre** [comment] 2017-05-25 14:12
I am not sure how you can fix this because **ProtocolSupport** is doing something with protocolib that makes the plugin "Reflex" useless (i think).

**Comment by OWERLORD01** [comment] 2017-05-25 14:13
> I am not sure how you can fix this because ProtocolSupport is doing something with protocolib that makes the plugin "Reflex" useless (i think).

I hope that she'll fix it :)

**Comment by OWERLORD01** [comment] 2017-05-25 14:13
I really need ProtocolSupport

**Comment by MeGysssTaa** [comment] 2017-05-25 14:21
If this is not caused by ProtocolSupport, this is fixed in the next update. Otherwise, I won't care about it since supporting ProtocolSupport is nearly impossible.

**Comment by OWERLORD01** [comment] 2017-05-25 14:32
> If this is not caused by ProtocolSupport, this is fixed in the next update. Otherwise, I won't care about it since supporting ProtocolSupport is nearly impossible.

I tried to remove protocolsupport. Now, when npc spawns, it kicks player for an pretty weird reason (java.outofsomething)

**Comment by OWERLORD01** [comment] 2017-05-25 14:34
So this plugin is not supporting protocolsupport... Good... I'll probably switch to aac again xD

**Comment by OWERLORD01** [comment] 2017-05-25 14:37
I think this error is not showing in 1.8.8

**Comment by MeGysssTaa** [comment] 2017-05-25 14:42
Read my messages carefully before spamming, please. I wrote than this has been fixed in the next release. If it will still persist for you, than it's incompatible with PS.

**Comment by OWERLORD01** [comment] 2017-05-25 14:44
> Read my messages carefully before spamming, please. I wrote than this has been fixed in the next release. If it will still persist for you, than it's incompatible with PS.

Ok, hope you fix it soon. Btw, its not issue with ps, i tested it without protocolsupport and it's still not working

**Closed** 2017-05-25 15:31 UTC
Labels: Bug
