### ISSUE TITLE
console_verbose not functioning

### ISSUE THREAD

**Issue by elstur** [MeGysssTaa/ReflexIssueTracker#196] opened 2017-12-17 01:17 UTC
By creating this issue on the Reflex Issue Tracker, I agree that I have fully and accurately read and understood everything stated in it's [Guide on this page](https://goo.gl/wUwZVk). I understand and agree that this issue can be ignored, closed or labeled "Invalid" without any further comments from Reflex maintainers if this issue doesn't match [the Guide](https://goo.gl/wUwZVk) entirely and properly.

I know and understand which cheats does Reflex check for, and which it doesn't. I clearly understand that there are no any movement checks and similar at the moment. I confirm that I am not running any possibly incompatible plugins or mods and my server core is either Spigot or PaperSpigot. I confirm that I will actively cooperate with Reflex maintainers in order to solve this issue as soon as possible.

By erasing this text I understand that this issue will most likely be deleted or ignored.

## General
**ISSUE TYPE**

Bypass／false positive／bug／console error／feature request／question

＞ bug

Console_verbose is not sending verbose messages in console when set to true

**Comment by MatrixTunnel** [comment] 2017-12-17 01:27
Duplicate of #187

**Comment by Hyronymos** [comment] 2017-12-17 01:28
Duplicate f #187 ? wut?

**Comment by MeGysssTaa** [comment] 2017-12-17 19:08
It works fine. The problem is on your side.
![scr](https://sc.reflex.rip/7qZRyk.png)

**Closed** 2017-12-17 19:09 UTC
